### ISSUE TITLE
Api key and limits

### ISSUE THREAD

**Issue by supafoundation** [Ankr-network/ankrscan.js#1]
Hi, thanks for this sdk. Just wanted to find out which api key this requires and the limits for the multichain rpc per ip and/or key

**Comment by fasashen** [comment]
Hi, thanks for your interest. During the early stage of development, the API key is not yet required, and limits are still not defined. Feel free to experiment!

**Comment by supafoundation** [comment]
Thank you for this. We are planning to use this long term would appreciate a rough ball park pricing and rate limit. Otherwise can discuss privately
